name: Xin Huang
markdown: kramdown
url: https://github.com/xin-huang/xin-huang.github.io/blob/master
github_username: xin-huang
orcid: 0000-0002-9918-9602
researchgate_username: Xin_Huang39
linkedin_username: xin-huang-96897885